Add readme FAQ
scs/substrate-api-client pull request #682
Opened 2023-12-05 07:53 UTC by haerdib

2023-12-05 08:52 UTC, masapr commented on README.md
> +3. Q: I want to retrieve a state from my node via the api-client, but I do not get the expected value respective the decoding fails. How come?
Same as above, I would not assume, that the person asking the question has their own node (instead of "my" I would write "a substrate node"

2023-12-05 12:13 UTC, haerdib commented on README.md
> +    A: When specifying your own state query, you must provide the return type of the state you're trying to retrieve. This is because the api-client only gets bytes from the node and must be able to
True. But I think it is still noteworthy because this has already led to confusion in the past. I adapted the text - what do you think?

2023-12-05 13:07 UTC, masapr requested changes
just one minor remark. Apart from that 👍

2023-12-05 13:07 UTC, masapr commented on README.md
>      A: First, ensure the api-client and the Substrate node have a matching version. E.g. if you're running your node on `release-polkadot-v1.2.0`, checkout and compile a matching branch of the api-cl
... same as above "your node"

2023-12-05 13:07 UTC, masapr commented on README.md
> -3. Q: I want to retrieve a state from my node via the api-client, but I do not get the expected value respective the decoding fails. How come?
Very nice, the whole paragraph is much more understandable now! 🎉

2023-12-07 08:39 UTC, masapr approved these changes
perfect, thanks!

2023-12-07 08:43 UTC, merged